baseurl = "https://metakits.cc"
languageCode = "en"
title = "Metakits"
theme = ["kiss"]
copyright = "&copy; <a href=\"/cv/simple/\">Metakits</a> 2024"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params]
style = "default"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Metakits.cc" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "picxenk"
github = "picxenk"
email = "picxenk@gmail.com"
linkedin = ""
facebook = "seungbum.kim.54"
instagram = ""
codepen = ""

#[params.matomoAnalytics]
#siteID = 1
#rootURL = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[params.sections_left]
"/cv/simple/" = "About"
"/projects" = "Projects"
"/teachings" = "Teachings"
"/writings" = "Writings"
"/tinkerings" = "Tinkerings"

[params.sections_right]
